# Markdownlint configuration file
default: true
first-line-heading: false
header-increment: false
line-length: false
no-duplicate-header:
    siblings_only: true
no-inline-html: 
    allowed_elements:
        - a
        - div
        - i
        - iframe
        - section
        - img
        - li
        - p
        - script
        - small
        - ul
no-multiple-blanks: 0