repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint.json"]

  - repo: local
    hooks:
      - id: astro-check
        name: Astro Type Check
        entry: npm run check
        language: system
        pass_filenames: false
        files: \.(astro|ts|tsx)$
