language: ruby
rvm:
- 2.5.0

install:
  # Install bundle
  - bundle install --jobs=3 --retry=3
  # Build website
  - bundle exec jekyll build
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli

script:
  # Proof the html
  - bundle exec htmlproofer ./_site --check-favicon --check-html --disable-external --url-ignore /\#À/,/\#Ä/
  # Lint the markdown
  - markdownlint . -c markdownlint.yml

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
