name: build-cv

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches:
      - main
    paths:
      - src/data/CV-MGarcia.tex
      - src/data/biblio.bib

# Allow this job to clone the repo and create a cv build
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent build
concurrency:
  group: "cv"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Nextflow
        run: |
          export NXF_VER=25.10.4
          curl -fsSL https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/nextflow
          nextflow -version

      - name: Compile latest CV
        run: nextflow run maxulysse/compile-latex -r 3.0.1 -profile docker --outdir . --github_avatar 'https://avatars.githubusercontent.com/u/1019628?s=300&v=4' --input src/data/CV-MGarcia.tex --outname CV-MGarcia-latest.pdf --biblio src/data/biblio.bib

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to cv branch
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B cv
          git add -f CV-MGarcia-latest.pdf
          git commit -m "Update CV - $(date +%Y-%m-%d)"
          git push -f origin cv
